### PR TITLE
Added responsiveness and readme

### PR DESCRIPTION
**Pull request by vrinda-mahajan**
Added 
- Responsiveness 
- readme

Live: https://flora-ui.netlify.app/

### CODE REVIEW

**Review by Maianki — APPROVED** [review]
LGTM

**Review by VLeads — COMMENTED** [review]
Everything looks good. The thing I noticed is in mobile view when hamburger menu is opened. It should close when I click outside of the menu. It will give a good user experience.

**Comment by vrinda-mahajan** [comment]
> 

Thank you @VLeads for mentioning it. I have fixed it.

**Review by foolhardy21 — APPROVED** [review]
Looks good to me.

**Pull request merged**
