### PR TITLE
Rating and toast

### PR DESCRIPTION
**Pull request by vrinda-mahajan**
Added rating and toast component to the documentation of CL. Please review my PR.

Preview
Rating: https://heuristic-brown-175672.netlify.app/docs#Rating
Toast: https://heuristic-brown-175672.netlify.app/docs#Toast

### CODE REVIEW

**Review by vrx29 — APPROVED** [review]
looks good to me you can merge it.

**Review by venkateshwarans — APPROVED** [review]
Looks good to me. Don't forget to add `Rating` & `Toast` to the side menu.

**Comment by vrinda-mahajan** [comment]
> Looks good to me. Don't forget to add `Rating` & `Toast` to the side menu.

Yes, thanks for reminding me.

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me.

**Pull request merged**
